services:
  app:
    container_name: mini-reddit-api
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=3000
        - MONGO_URI=mongodb://hubadmin:toto@mongo:27017/mini-redit?retryWrites=true&authSource=admin
        - JWT_SECRET=9bbad78d1e8e5e346b3f991c39e3cd76

    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    container_name: mini-reddit-mongo
    image: mongo:8.2.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hubadmin
      - MONGO_INITDB_ROOT_PASSWORD=toto
      - MONGO_INITDB_DATABASE=mini-reddit
    volumes:
      - mini-reddit-mongo-data:/data/db
    restart: unless-stopped
volumes:
  mini-reddit-mongo-data:
